### ISSUE TITLE
 solax_api_charge_added_total incorrect spikes

### ISSUE THREAD

**Issue by PatrikTrestik** [PatrikTrestik/homeassistant-solax-http#73]
Hi Patrik,

would it be possible to implement filtering of the solax_api_charge_added_total entity.
Every now and then, it reports values of hundreds or thousands of kWh only to return back to the previous value in next sample.
The filter value could be calculated with the help of max charging power and sampling rate.
In my case of X3 11kW and if my math is correct, the 10sec increment should not be more than 0.05kWh

![image](https://github.com/user-attachments/assets/d0ac649a-06bb-4401-b0eb-759525ed8c6e)

Cheers,
Libor

_Originally posted by @liborson in https://github.com/PatrikTrestik/homeassistant-solax-http/discussions/72_

**Comment by PatrikTrestik** [comment]
This is definitely bug.

Filtering makes no sense, better to fix core issue. I'll look on it this week.

**Comment by PatrikTrestik** [comment]
I quickly checked my sensor, but I see no spikes here.

![Image](https://github.com/user-attachments/assets/a851a34b-08f6-4e33-a353-65f7aac8f948)

Please send me your device info:

![Image](https://github.com/user-attachments/assets/60666ee0-3dee-4c1e-8060-7c705ac1adbc)

And integration version.

Thanks.

**Comment by liborson** [comment]
It may very well be. But it could also be a bug inside the charger itself.
Reporting some funny values.

Díky,
Libor

**Comment by liborson** [comment]
The spikes are kind of random, during idle periods, where nothing is
happening.
Integration was updated today, so that won't help I am afraid. Those spikes
are from some time back. Now I am on 1.4.1

Here you go. As I can see, you have newer fw. Will try to check if I can
get it upgraded as well.
[image: image.png]

Libor

**Comment by PatrikTrestik** [comment]
Actually, there ware few issues in integration which I fixed recently. 
Let it run for some time, I hope that it will not happen again.

**Comment by PatrikTrestik** [comment]
@liborson do you still experience spikes?

**Comment by liborson** [comment]
Hi Patrik,

still the same, see below.

[image: image.png]

[image: image.png]

Cheers,
Libor

**Comment by PatrikTrestik** [comment]
Closing for inactivity. 

Feel free to reopen if there are still problems.
